import React, { useState, useEffect } from "react";
import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useAppSelector, useAppDispatch } from "../src/hooks/redux-hooks";
import { setProducts } from "../src/store/Reducers/products";
import { addItemsToCart } from "../src/store/Reducers/cart";
import Spinner from "../src/components/Layout/Spinner";
import { useAlert } from "react-alert";
import categories from "../src/utils/categories";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter()
  const { token,userDetails } = useAppSelector((state) => state.userReducer);
  const { products } = useAppSelector((state) => state.productsReducer);
  const [loading, setLoading] = useState(false);
  const alert = useAlert();
  const dispatch = useAppDispatch();

  function loadScript(src: any) {
    return new Promise((resolve) => {
      const script = document.createElement("script");
      script.src = src;
      script.onload = () => {
        resolve(true);
      };
      script.onerror = () => {
        resolve(false);
      };
      document.body.appendChild(script);
    });
  }
  // Then I'll add the function displayRazorpay that will first load the script, then make a post request to our back-end route and finally show the popup.
  async function displayRazorpay() {
    const res = await loadScript("https://checkout.razorpay.com/v1/checkout.js");
  
    if (!res) {
      alert.error("Razorpay SDK failed to load. Are you online?");
      return;
    }
  
    let token = JSON.parse(
      JSON.parse(localStorage.getItem("persist:root") as any).userReducer
    ).token;
    console.log(token);
    const config = {
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${token}`,
      },
    };
  
    const { data } = await axios.get(
      `${process.env.NEXT_PUBLIC_API_URL}/user/primeRequest`,
      config 
    );
    // creating a new order
    // const {data} = await sendRequest(
    //   `${process.env.NEXT_PUBLIC_API_URL}/order/createOrder`,
    //   payload,
    //   "POST",
    // );
      console.log(data); 
      
    if (!data) {
      alert.error("Server error. Are you online?");
      return;
    }
  
    // Getting the order details back
    const { amount, id: order_id, currency } = data.primeDetail;

  
    const options = {
      key: "rzp_test_vfKqDSJFUHzSxG", // Enter the Key ID generated from the Dashboard
      amount: amount.toString(),
      currency: currency,
      name: "QUDE Corp.",
      description: "Test Transaction",
      image: "/img/logo.jpg",
      order_id: order_id,
      handler: async function (response: any) {
        const paymentInfo = {
          orderCreationId: order_id,
          razorpayPaymentId: response.razorpay_payment_id,
          razorpayOrderId: response.razorpay_order_id,
          razorpaySignature: response.razorpay_signature,
        };
     
        const data = {
          paymentInfo
        };
        console.log(data);
  
        const config = {
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token}`,
          },
        };
        const result = await axios.post(
          `${process.env.NEXT_PUBLIC_API_URL}/user/payment/status`,
          data,
          config
        );
  

        alert.success(result.data.message);
      },
      prefill: {
        name: userDetails.name || "Example",
        email: "example@test.com",
        contact: userDetails.phone || "999999999",
      },
      notes: {
        address: "QUDE Pvt Ltd.",
      },
      theme: {
        color: "#61dafb",
      },
    };
  
    const paymentObject = new window.Razorpay(options);
    paymentObject.open();
  } 


  const primeHandler=()=>{
    displayRazorpay();
  }

 
  return (
    <React.Fragment>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {loading ? (
          <main
            style={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              width: "100vw",
              height: "80vh",
              zIndex: 100,
            }}
          >
            <Spinner />
          </main>
        ) : (
          <React.Fragment>
            <main className="page-wrapper">
              {/* <!-- Hero section--> */}
              <section
                className="bg-accent bg-position-top-center bg-repeat-0 py-5"
                style={{
                  backgroundImage: "url(img/home/marketplace-hero.jpg)",
                }}
              >
                <div className="pb-lg-5 mb-lg-3">
                  <div className="container py-lg-5 my-lg-5">
                    <div className="row mb-4 mb-sm-5">
                      <div className="col-lg-7 col-md-9 text-center text-sm-start">
                        <h1 className="text-white lh-base">
                          <span className="fw-light">Over</span> 1,500{" "}
                          <span className="fw-light">curated</span> Design{" "}
                          <span className="fw-light">resources</span>, Images,
                          Graphic <span className="fw-light">&amp;</span>{" "}
                          Website <span className="fw-light">templates</span>
                        </h1>
                        <h2 className="h5 text-white fw-light">
                          High quality items created by our global community
                        </h2>
                      </div>
                    </div>
                    <div className="row pb-lg-5 mb-4 mb-sm-5">
                      <div className="col-lg-6 col-md-8">
                        <div className="input-group input-group-lg flex-nowrap">
                       
                          <button
                            className="btn btn-primary btn-lg fs-base"
                            type="button"
                            onClick={primeHandler}
                          >
                            Join Prime
                          </button>
                  
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
              {/* <!-- Categories products (Carousel)--> */}
              <div className="container pb-4 pb-sm-5">
                <h2 className="h3 text-center py-4 mt-md-3">Categories</h2>

                {/* <!-- Categories grid--> */}
                <div className="row pt-5">
                  {/* <!-- Catogory--> */}
                  {categories.map((category: any) => {
                    return (
                      <div
                        className="col-md-4 col-sm-6 mb-3"
                        key={category.name}
                      >
                        <div className="card border-0">
                          <Link href={`/category/${category.name}`}>
                            <a
                              className="d-block overflow-hidden rounded-3"
                              href="#"
                            >
                              <img
                                className="d-block w-100"
                                src={category.image}
                                alt={category.name}
                                style={{ maxHeight: "300px" }}
                              />
                            </a>
                          </Link>

                          <div className="card-body">
                            <h2 className="h5">{category.name}</h2>
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
              {/* <!-- Marketplace features--> */}
              <section
                className="bg-accent bg-size-cover bg-position-center pt-5 pb-4 pb-lg-5"
                style={{
                  backgroundImage:
                    "url(img/marketplace/features/features-bg.jpg)",
                }}
              >
                <div className="container pt-lg-3">
                  <h2 className="h3 mb-3 pb-4 text-light text-center">
                    Why our marketplace?
                  </h2>
                  <div className="row pt-lg-2 text-center">
                    <div className="col-lg-3 col-sm-6 mb-grid-gutter">
                      <div className="d-inline-flex align-items-center text-start">
                        <img
                          src="img/marketplace/features/quality.png"
                          width="52"
                          alt="Quality Guarantee"
                        />
                        <div className="ps-3">
                          <h6 className="text-light fs-base mb-1">
                            Quality Guarantee
                          </h6>
                          <p className="text-light fs-ms opacity-70 mb-0">
                            Quality checked by our team
                          </p>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-3 col-sm-6 mb-grid-gutter">
                      <div className="d-inline-flex align-items-center text-start">
                        <img
                          src="img/marketplace/features/support.png"
                          width="52"
                          alt="Customer Support"
                        />
                        <div className="ps-3">
                          <h6 className="text-light fs-base mb-1">
                            Customer Support
                          </h6>
                          <p className="text-light fs-ms opacity-70 mb-0">
                            Friendly 24/7 customer support
                          </p>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-3 col-sm-6 mb-grid-gutter">
                      <div className="d-inline-flex align-items-center text-start">
                        <img
                          src="img/marketplace/features/updates.png"
                          width="52"
                          alt="Free Updates"
                        />
                        <div className="ps-3">
                          <h6 className="text-light fs-base mb-1">
                            Lifetime Free Updates
                          </h6>
                          <p className="text-light fs-ms opacity-70 mb-0">
                            Never pay for an update
                          </p>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-3 col-sm-6 mb-grid-gutter">
                      <div className="d-inline-flex align-items-center text-start">
                        <img
                          src="img/marketplace/features/secure.png"
                          width="52"
                          alt="Secure Payments"
                        />
                        <div className="ps-3">
                          <h6 className="text-light fs-base mb-1">
                            Secure Payments
                          </h6>
                          <p className="text-light fs-ms opacity-70 mb-0">
                            We posess SSL / Secure сertificate
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
              <div className="container pb-4 pb-sm-5">
                {/* <!-- Popular brands--> */}
                <h2 className="h3 text-center py-4 mt-md-3">Popular brands</h2>
                <div className="row">
                  <div className="col-md-3 col-sm-4 col-6">
                    <a
                      className="d-block bg-white shadow-sm rounded-3 py-3 py-sm-4 mb-grid-gutter"
                      href="#"
                    >
                      <img
                        className="d-block mx-auto"
                        src="/img/shop/brands/01.png"
                        width="150"
                        alt="Brand"
                      />
                    </a>
                  </div>
                  <div className="col-md-3 col-sm-4 col-6">
                    <a
                      className="d-block bg-white shadow-sm rounded-3 py-3 py-sm-4 mb-grid-gutter"
                      href="#"
                    >
                      <img
                        className="d-block mx-auto"
                        src="/img/shop/brands/02.png"
                        width="150"
                        alt="Brand"
                      />
                    </a>
                  </div>
                  <div className="col-md-3 col-sm-4 col-6">
                    <a
                      className="d-block bg-white shadow-sm rounded-3 py-3 py-sm-4 mb-grid-gutter"
                      href="#"
                    >
                      <img
                        className="d-block mx-auto"
                        src="/img/shop/brands/03.png"
                        width="150"
                        alt="Brand"
                      />
                    </a>
                  </div>
                  <div className="col-md-3 col-sm-4 col-6">
                    <a
                      className="d-block bg-white shadow-sm rounded-3 py-3 py-sm-4 mb-grid-gutter"
                      href="#"
                    >
                      <img
                        className="d-block mx-auto"
                        src="/img/shop/brands/04.png"
                        width="150"
                        alt="Brand"
                      />
                    </a>
                  </div>
                  <div className="col-md-3 col-sm-4 col-6">
                    <a
                      className="d-block bg-white shadow-sm rounded-3 py-3 py-sm-4 mb-grid-gutter"
                      href="#"
                    >
                      <img
                        className="d-block mx-auto"
                        src="/img/shop/brands/05.png"
                        width="150"
                        alt="Brand"
                      />
                    </a>
                  </div>
                  <div className="col-md-3 col-sm-4 col-6">
                    <a
                      className="d-block bg-white shadow-sm rounded-3 py-3 py-sm-4 mb-grid-gutter"
                      href="#"
                    >
                      <img
                        className="d-block mx-auto"
                        src="/img/shop/brands/06.png"
                        width="150"
                        alt="Brand"
                      />
                    </a>
                  </div>
                  <div className="col-md-3 col-sm-4 col-6">
                    <a
                      className="d-block bg-white shadow-sm rounded-3 py-3 py-sm-4 mb-grid-gutter"
                      href="#"
                    >
                      <img
                        className="d-block mx-auto"
                        src="/img/shop/brands/07.png"
                        width="150"
                        alt="Brand"
                      />
                    </a>
                  </div>
                  <div className="col-md-3 col-sm-4 col-6">
                    <a
                      className="d-block bg-white shadow-sm rounded-3 py-3 py-sm-4 mb-grid-gutter"
                      href="#"
                    >
                      <img
                        className="d-block mx-auto"
                        src="/img/shop/brands/08.png"
                        width="150"
                        alt="Brand"
                      />
                    </a>
                  </div>
                  <div className="col-md-3 col-sm-4 col-6">
                    <a
                      className="d-block bg-white shadow-sm rounded-3 py-3 py-sm-4 mb-grid-gutter"
                      href="#"
                    >
                      <img
                        className="d-block mx-auto"
                        src="/img/shop/brands/09.png"
                        width="150"
                        alt="Brand"
                      />
                    </a>
                  </div>
                  <div className="col-md-3 col-sm-4 col-6">
                    <a
                      className="d-block bg-white shadow-sm rounded-3 py-3 py-sm-4 mb-grid-gutter"
                      href="#"
                    >
                      <img
                        className="d-block mx-auto"
                        src="/img/shop/brands/10.png"
                        width="150"
                        alt="Brand"
                      />
                    </a>
                  </div>
                  <div className="col-md-3 col-sm-4 col-6">
                    <a
                      className="d-block bg-white shadow-sm rounded-3 py-3 py-sm-4 mb-grid-gutter"
                      href="#"
                    >
                      <img
                        className="d-block mx-auto"
                        src="/img/shop/brands/11.png"
                        width="150"
                        alt="Brand"
                      />
                    </a>
                  </div>
                  <div className="col-md-3 col-sm-4 col-6">
                    <a
                      className="d-block bg-white shadow-sm rounded-3 py-3 py-sm-4 mb-grid-gutter"
                      href="#"
                    >
                      <img
                        className="d-block mx-auto"
                        src="/img/shop/brands/12.png"
                        width="150"
                        alt="Brand"
                      />
                    </a>
                  </div>
                </div>
              </div>
              {/* <!-- Recent products grid--> */}
              <section className="container pb-5 mb-lg-3">
                {/* <!-- Heading--> */}
                <div className="d-flex flex-wrap justify-content-between align-items-center pt-1 border-bottom pb-4 mb-4">
                  <h2 className="h3 mb-0 pt-3 me-2">
                    The most recent releases
                  </h2>
                  <div className="pt-3">
                    <select className="form-select me-2">
                      <option>All categories</option>
                      <option>Photos</option>
                      <option>Graphics</option>
                      <option>UI Design</option>
                      <option>Web Themes</option>
                      <option>Fonts</option>
                      <option>Add-Ons</option>
                    </select>
                  </div>
                </div>
                {/* <!-- Grid--> */}
                <div className="row pt-2 mx-n2">
                  {/* <!-- Product--> */}
                  <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-grid-gutter">
                    {/* <!-- Product--> */}
                    <div className="card product-card-alt">
                      <div className="product-thumb">
                        <button className="btn-wishlist btn-sm" type="button">
                          <i className="ci-heart"></i>
                        </button>
                        <div className="product-card-actions">
                          <a
                            className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                            href="marketplace-single.html"
                          >
                            <i className="ci-eye"></i>
                          </a>
                          <button
                            className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                            type="button"
                          >
                            <i className="ci-cart"></i>
                          </button>
                        </div>
                        <a
                          className="product-thumb-overlay"
                          href="marketplace-single.html"
                        ></a>
                        <img
                          src="img/marketplace/products/01.jpg"
                          alt="Product"
                        />
                      </div>
                      <div className="card-body">
                        <div className="d-flex flex-wrap justify-content-between align-items-start pb-2">
                          <div className="text-muted fs-xs me-1">
                            by{" "}
                            <a className="product-meta fw-medium" href="#">
                              Createx Std.{" "}
                            </a>
                            in{" "}
                            <a className="product-meta fw-medium" href="#">
                              UI Design
                            </a>
                          </div>
                          <div className="star-rating">
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-half active"></i>
                            <i className="star-rating-icon ci-star"></i>
                          </div>
                        </div>
                        <h3 className="product-title fs-sm mb-2">
                          <a href="marketplace-single.html">
                            Square Style Mobile UI Kit (Sketch)
                          </a>
                        </h3>
                        <div className="d-flex flex-wrap justify-content-between align-items-center">
                          <div className="fs-sm me-2">
                            <i className="ci-download text-muted me-1"></i>153
                            <span className="fs-xs ms-1">Sales</span>
                          </div>
                          <div className="bg-faded-accent text-accent rounded-1 py-1 px-2">
                            $24.<small>00</small>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* <!-- Product--> */}
                  <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-grid-gutter">
                    <div className="card product-card-alt">
                      <div className="product-thumb">
                        <button className="btn-wishlist btn-sm" type="button">
                          <i className="ci-heart"></i>
                        </button>
                        <div className="product-card-actions">
                          <a
                            className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                            href="marketplace-single.html"
                          >
                            <i className="ci-eye"></i>
                          </a>
                          <button
                            className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                            type="button"
                          >
                            <i className="ci-cart"></i>
                          </button>
                        </div>
                        <a
                          className="product-thumb-overlay"
                          href="marketplace-single.html"
                        ></a>
                        <img
                          src="img/marketplace/products/04.jpg"
                          alt="Product"
                        />
                      </div>
                      <div className="card-body">
                        <div className="d-flex flex-wrap justify-content-between align-items-start pb-2">
                          <div className="text-muted fs-xs me-1">
                            by{" "}
                            <a className="product-meta fw-medium" href="#">
                              Createx Std.{" "}
                            </a>
                            in{" "}
                            <a className="product-meta fw-medium" href="#">
                              Graphics
                            </a>
                          </div>
                          <div className="star-rating">
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                          </div>
                        </div>
                        <h3 className="product-title fs-sm mb-2">
                          <a href="marketplace-single.html">
                            Flat-line E-Commerce Icons (AI)
                          </a>
                        </h3>
                        <div className="d-flex flex-wrap justify-content-between align-items-center">
                          <div className="fs-sm me-2">
                            <i className="ci-download text-muted me-1"></i>26
                            <span className="fs-xs ms-1">Sales</span>
                          </div>
                          <div className="bg-faded-accent text-accent rounded-1 py-1 px-2">
                            $18.<small>00</small>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* <!-- Product--> */}
                  <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-grid-gutter">
                    <div className="card product-card-alt">
                      <div className="product-thumb">
                        <button className="btn-wishlist btn-sm" type="button">
                          <i className="ci-heart"></i>
                        </button>
                        <div className="product-card-actions">
                          <a
                            className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                            href="marketplace-single.html"
                          >
                            <i className="ci-eye"></i>
                          </a>
                          <button
                            className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                            type="button"
                          >
                            <i className="ci-cart"></i>
                          </button>
                        </div>
                        <a
                          className="product-thumb-overlay"
                          href="marketplace-single.html"
                        ></a>
                        <img
                          src="img/marketplace/products/09.jpg"
                          alt="Product"
                        />
                      </div>
                      <div className="card-body">
                        <div className="d-flex flex-wrap justify-content-between align-items-start pb-2">
                          <div className="text-muted fs-xs me-1">
                            by{" "}
                            <a className="product-meta fw-medium" href="#">
                              pixels
                            </a>
                            in{" "}
                            <a className="product-meta fw-medium" href="#">
                              UI Design
                            </a>
                          </div>
                          <div className="star-rating">
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star"></i>
                          </div>
                        </div>
                        <h3 className="product-title fs-sm mb-2">
                          <a href="marketplace-single.html">
                            Isometric Device Mockups (PSD)
                          </a>
                        </h3>
                        <div className="d-flex flex-wrap justify-content-between align-items-center">
                          <div className="fs-sm me-2">
                            <i className="ci-download text-muted me-1"></i>36
                            <span className="fs-xs ms-1">Sales</span>
                          </div>
                          <div className="bg-faded-accent text-accent rounded-1 py-1 px-2">
                            $16.<small>00</small>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* <!-- Product--> */}
                  <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-grid-gutter">
                    <div className="card product-card-alt">
                      <div className="product-thumb">
                        <button className="btn-wishlist btn-sm" type="button">
                          <i className="ci-heart"></i>
                        </button>
                        <div className="product-card-actions">
                          <a
                            className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                            href="marketplace-single.html"
                          >
                            <i className="ci-eye"></i>
                          </a>
                          <button
                            className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                            type="button"
                          >
                            <i className="ci-cart"></i>
                          </button>
                        </div>
                        <a
                          className="product-thumb-overlay"
                          href="marketplace-single.html"
                        ></a>
                        <img
                          src="img/marketplace/products/10.jpg"
                          alt="Product"
                        />
                      </div>
                      <div className="card-body">
                        <div className="d-flex flex-wrap justify-content-between align-items-start pb-2">
                          <div className="text-muted fs-xs me-1">
                            by{" "}
                            <a className="product-meta fw-medium" href="#">
                              theDesigner{" "}
                            </a>
                            in{" "}
                            <a className="product-meta fw-medium" href="#">
                              Graphics
                            </a>
                          </div>
                          <div className="star-rating">
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star"></i>
                          </div>
                        </div>
                        <h3 className="product-title fs-sm mb-2">
                          <a href="marketplace-single.html">
                            Coffe Paper Cup Mockup
                          </a>
                        </h3>
                        <div className="d-flex flex-wrap justify-content-between align-items-center">
                          <div className="fs-sm me-2">
                            <i className="ci-download text-muted me-1"></i>57
                            <span className="fs-xs ms-1">Sales</span>
                          </div>
                          <div className="bg-faded-accent text-accent rounded-1 py-1 px-2">
                            $10.<small>00</small>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* <!-- Product--> */}
                  <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-grid-gutter">
                    <div className="card product-card-alt">
                      <div className="product-thumb">
                        <button className="btn-wishlist btn-sm" type="button">
                          <i className="ci-heart"></i>
                        </button>
                        <div className="product-card-actions">
                          <a
                            className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                            href="marketplace-single.html"
                          >
                            <i className="ci-eye"></i>
                          </a>
                          <button
                            className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                            type="button"
                          >
                            <i className="ci-cart"></i>
                          </button>
                        </div>
                        <a
                          className="product-thumb-overlay"
                          href="marketplace-single.html"
                        ></a>
                        <img
                          src="img/marketplace/products/06.jpg"
                          alt="Product"
                        />
                      </div>
                      <div className="card-body">
                        <div className="d-flex flex-wrap justify-content-between align-items-start pb-2">
                          <div className="text-muted fs-xs me-1">
                            by{" "}
                            <a className="product-meta fw-medium" href="#">
                              Createx Std.{" "}
                            </a>
                            in{" "}
                            <a className="product-meta fw-medium" href="#">
                              Graphics
                            </a>
                          </div>
                          <div className="star-rating">
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                          </div>
                        </div>
                        <h3 className="product-title fs-sm mb-2">
                          <a href="marketplace-single.html">
                            Travel &amp; Landmark Icon Pack (AI)
                          </a>
                        </h3>
                        <div className="d-flex flex-wrap justify-content-between align-items-center">
                          <div className="fs-sm me-2">
                            <i className="ci-download text-muted me-1"></i>21
                            <span className="fs-xs ms-1">Sales</span>
                          </div>
                          <div className="bg-faded-accent text-accent rounded-1 py-1 px-2">
                            $17.<small>00</small>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* <!-- Product--> */}
                  <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-grid-gutter">
                    <div className="card product-card-alt">
                      <div className="product-thumb">
                        <button className="btn-wishlist btn-sm" type="button">
                          <i className="ci-heart"></i>
                        </button>
                        <div className="product-card-actions">
                          <a
                            className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                            href="marketplace-single.html"
                          >
                            <i className="ci-eye"></i>
                          </a>
                          <button
                            className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                            type="button"
                          >
                            <i className="ci-cart"></i>
                          </button>
                        </div>
                        <a
                          className="product-thumb-overlay"
                          href="marketplace-single.html"
                        ></a>
                        <img
                          src="img/marketplace/products/05.jpg"
                          alt="Product"
                        />
                      </div>
                      <div className="card-body">
                        <div className="d-flex flex-wrap justify-content-between align-items-start pb-2">
                          <div className="text-muted fs-xs me-1">
                            by{" "}
                            <a className="product-meta fw-medium" href="#">
                              Createx Std.{" "}
                            </a>
                            in{" "}
                            <a className="product-meta fw-medium" href="#">
                              UI Design
                            </a>
                          </div>
                          <div className="star-rating">
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star"></i>
                          </div>
                        </div>
                        <h3 className="product-title fs-sm mb-2">
                          <a href="marketplace-single.html">
                            Minimal Mobile App UI Kit (Sketch)
                          </a>
                        </h3>
                        <div className="d-flex flex-wrap justify-content-between align-items-center">
                          <div className="fs-sm me-2">
                            <i className="ci-download text-muted me-1"></i>117
                            <span className="fs-xs ms-1">Sales</span>
                          </div>
                          <div className="bg-faded-accent text-accent rounded-1 py-1 px-2">
                            $23.<small>00</small>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* <!-- Product--> */}
                  <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-grid-gutter">
                    <div className="card product-card-alt">
                      <div className="product-thumb">
                        <button className="btn-wishlist btn-sm" type="button">
                          <i className="ci-heart"></i>
                        </button>
                        <div className="product-card-actions">
                          <a
                            className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                            href="marketplace-single.html"
                          >
                            <i className="ci-eye"></i>
                          </a>
                          <button
                            className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                            type="button"
                          >
                            <i className="ci-cart"></i>
                          </button>
                        </div>
                        <a
                          className="product-thumb-overlay"
                          href="marketplace-single.html"
                        ></a>
                        <img
                          src="img/marketplace/products/11.jpg"
                          alt="Product"
                        />
                      </div>
                      <div className="card-body">
                        <div className="d-flex flex-wrap justify-content-between align-items-start pb-2">
                          <div className="text-muted fs-xs me-1">
                            by{" "}
                            <a className="product-meta fw-medium" href="#">
                              pixels
                            </a>
                            in{" "}
                            <a className="product-meta fw-medium" href="#">
                              Graphics
                            </a>
                          </div>
                          <div className="star-rating">
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-half active"></i>
                            <i className="star-rating-icon ci-star"></i>
                            <i className="star-rating-icon ci-star"></i>
                          </div>
                        </div>
                        <h3 className="product-title fs-sm mb-2">
                          <a href="marketplace-single.html">
                            Printed T-Shirt Mockup (PSD)
                          </a>
                        </h3>
                        <div className="d-flex flex-wrap justify-content-between align-items-center">
                          <div className="fs-sm me-2">
                            <i className="ci-download text-muted me-1"></i>94
                            <span className="fs-xs ms-1">Sales</span>
                          </div>
                          <div className="bg-faded-accent text-accent rounded-1 py-1 px-2">
                            $12.<small>00</small>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {/* <!-- Product--> */}
                  <div className="col-lg-3 col-md-4 col-sm-6 px-2 mb-grid-gutter">
                    <div className="card product-card-alt">
                      <div className="product-thumb">
                        <button className="btn-wishlist btn-sm" type="button">
                          <i className="ci-heart"></i>
                        </button>
                        <div className="product-card-actions">
                          <a
                            className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                            href="marketplace-single.html"
                          >
                            <i className="ci-eye"></i>
                          </a>
                          <button
                            className="btn btn-light btn-icon btn-shadow fs-base mx-2"
                            type="button"
                          >
                            <i className="ci-cart"></i>
                          </button>
                        </div>
                        <a
                          className="product-thumb-overlay"
                          href="marketplace-single.html"
                        ></a>
                        <img
                          src="img/marketplace/products/12.jpg"
                          alt="Product"
                        />
                      </div>
                      <div className="card-body">
                        <div className="d-flex flex-wrap justify-content-between align-items-start pb-2">
                          <div className="text-muted fs-xs me-1">
                            by{" "}
                            <a className="product-meta fw-medium" href="#">
                              pixels
                            </a>
                            in{" "}
                            <a className="product-meta fw-medium" href="#">
                              Graphics
                            </a>
                          </div>
                          <div className="star-rating">
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star-filled active"></i>
                            <i className="star-rating-icon ci-star"></i>
                          </div>
                        </div>
                        <h3 className="product-title fs-sm mb-2">
                          <a href="marketplace-single.html">
                            Corporate Branding Mockup (PSD)
                          </a>
                        </h3>
                        <div className="d-flex flex-wrap justify-content-between align-items-center">
                          <div className="fs-sm me-2">
                            <i className="ci-download text-muted me-1"></i>122
                            <span className="fs-xs ms-1">Sales</span>
                          </div>
                          <div className="bg-faded-accent text-accent rounded-1 py-1 px-2">
                            $18.<small>00</small>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                {/* <!-- More button--> */}
                <div className="text-center">
                  <a
                    className="btn btn-outline-accent"
                    href="marketplace-category.html"
                  >
                    View more products
                    <i className="ci-arrow-right fs-ms ms-1"></i>
                  </a>
                </div>
              </section>
            </main>
          </React.Fragment>
        )}
      </div>
    </React.Fragment>
  );
};

export default Home;
